Rename Central Portal deployment env vars
OK, now I'm renaming the credentials, because my first release failed:

  Error: [ERROR] Unable to upload bundle for deployment: Deployment
  [INFO] java.lang.RuntimeException: Invalid request. Status: 401 Response body:
  [INFO]     at org.sonatype.central.publisher.client.httpclient.UploadPublisherEndpoint.call (UploadPublisherEndpoint.java:33)

I am not actually certain the user token changed (it may just be
that the legacy `OSSRH_USER=scijava-ci` value was the culprit), but
that's OK: going through the few orgs that actually deploy to Maven
Central to update to a new token is not really such a big hassle.