travis-javadoc: try to mitigate concurrency issues
It seems that Travis CI likes to run multiple cron jobs simultaneously,
so we are getting occasional build failures like this:

  == Updating javadoc.scijava.org repository ==
  [gh-pages c3cd451] Update Java3D javadocs (Travis build 100)
   3 files changed, 13 insertions(+), 13 deletions(-)
  To github.com:scijava/javadoc.scijava.org
   ! [rejected]        gh-pages -> gh-pages (fetch first)
  error: failed to push some refs to 'git@github.com:scijava/javadoc.scijava.org'
  hint: Updates were rejected because the remote contains work that you do
  hint: not have locally. This is usually caused by another repository pushing
  hint: to the same ref. You may want to first integrate the remote changes
  hint: (e.g., 'git pull ...') before pushing again.
  hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Doing another "pull --rebase" first may help avoid some of them.